service: serverlessnode

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: us-east-2

functions:
  listEC2Instances:
    handler: handler.listEC2Instances
    events:
      - http:
          path: listEC2Instances
          method: get

    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "ec2:Describe*"
          - "elasticloadbalancing:Describe*"
          - "autoscaling:Describe*"
          - "cloudwatch:ListMetrics"
          - "cloudwatch:GetMetricStatistics"
          - "cloudwatch:Describe*"
          - "logs:*"
        Resource: "*"
