service: serverlessnode

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: us-east-2

functions:
  listEC2Instances:
    handler: handler.listEC2Instances
    events:
      - http:
          path: listEC2Instances
          method: get

    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "ec2:Describe*"
        Resource: "*"

      - Effect: "Allow"
        Action: "elasticloadbalancing:Describe*"
        Resource: "*"

      - Effect: "Allow"
        Action: "autoscaling:Describe*"
        Resource: "*"

      - Effect: "Allow"
        Action:
          - "cloudwatch:ListMetrics"
          - "cloudwatch:GetMetricStatistics"
          - "cloudwatch:Describe*"
        Resource: "*"

      - Effect: "Allow"
        Action:
          - "logs:*"
        Resource: "*"
